### ISSUE TITLE
✅ To Do List...

### ISSUE THREAD

**Issue by oneezy** [oneezy/ui#1]
# Todo 
🟥 **Critical**  🟧 **High**  🟨 **Medium** 🟩 **Low**

> This is an incomplete brain dump of what I think needs to be accomplished for this thing to be at v1.0.0 status. 

## Features
- [ ] 🟥 Setup plop templates for components
- [ ] 🟥 Create npm publish workflow with Github Actions

<details>
  <summary><b>npm publish workflow</b></summary><br>
  
  1. plop component
  2. develops component
  3. git add .
  4. git commit -m "feat: new component"
  5. Husky does stuff...
  6. git push
  7. github action script...
      1. pnpm version patch | minor | major
      2. pnpm build (run-s story:build package:build)
      3. cd package
      4. npm publish --access public
      5. cd ..
</details>

- [ ] 🟧 custom themes (fonts/ colors/ utilities)
- [x] 🟨 ~~Remove `.cts` extensions from generating inside svelte package~~
- [ ] 🟩 Add Tailwind Container Queries plugin with examples

## Bugs
- [x] 🟥 ~~A major bug is stopping `@oneezy/ui` to be `npm install`'d. This has to do with the way were handing the "default" and "production" exports inside `package.json`.~~

<details>
  <summary><b>things to test...</b></summary><br>

- conditional svelte key
- export arrays
- set mode for "dev" or "prod"
  
</details>

- [ ] 🟥 When developing, `pnpm dev` and `pnpm build` both work but `pnpm preview` fails
- [ ] 🟧 Remove "scavenger" related wording and components

## Docs
- [x] 🟨 ~~Update README to explain how to use `@oneezy/ui` 's tailwind specific files as a base to create~~

## Questions
- [ ] 🟧 Should I use commitlint or changesets with the github action and does it matter? 
- [ ] 🟨 Do I really need 2 Tailwind and Postcss configs or is there a better way to?
- [ ] 🟨 Do I really need "1-9" on all primary/secondar/lite/dark classes? that's so much setup for themes each time.
